#!/usr/bin/env python3
"""GUI smoke test for Magnolius_VariMuCompressor.jsfx.

@gfx runs on the UI thread and NEVER runs in an offline render, so
render_test.py cannot reach the panel at all -- a @gfx section with a syntax
error still lets every render_test pass, including "params" (verified: a
deliberate `g_broken = ( ( ;` in @gfx left all 17 sliders enumerating).

This drives the panel for real. It generates a debug build from the shipped
source, floats the FX window in a throwaway REAPER instance (@gfx only runs
when the window is shown) and has @gfx publish results through hidden
sliders, which a ReaScript reads back.

What it pins:
  * @gfx compiles and actually runs (a frame counter advances);
  * a knob change actually reaches the AUDIO PATH. This is the one that
    matters: v0.1 shipped with every knob dead, because slider_automate()
    notifies the host but does NOT re-run @slider (nor does sliderchange(),
    and @block never runs on a stopped track), so nothing recomputed a single
    coefficient. Checking the host readback alone did NOT catch that -- the
    host saw the new value while the DSP kept the old one. So this reads back
    audio-side DERIVED state (`agc`, `l.threshv`), not slider values;
  * slider_automate(2^(n-1)) really notifies the host;
  * the panel keeps running after every slider is driven to its extremes.

What it does NOT pin: whether anything is legible or correctly laid out.
Scripted capture of a JSFX pane does not work here (xwd misses it, x11grab
returns black), but the desktop screenshot utility captures it fine -- so the
way to check appearance is to ask for a screenshot, not to automate one. That
is how the v0.1 dead-knob bug was spotted: the panel was drawing "RIGHT" and
"follows Left" while Mode said M/S, which is only possible if `agc` was
stale.

Runs in an isolated resource directory (-cfgfile), so your REAPER config is
untouched. Needs a graphical session.

Usage: gfx_test.py            (VARIMU_KEEP_DBG=1 keeps the generated build)
"""
import math
import os
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "Magnolius_VariMuCompressor.jsfx")
RES = os.path.expanduser("~/.config/REAPER")
WORK = os.environ.get("VARIMU_WORK",
                      os.path.expanduser("~/.cache/varimu-rendertest"))
DBG = "_VariMuGfxDbg.jsfx"

# Hidden (-prefixed) sliders carry results out of @gfx; slider_automate is the
# UI thread's only channel to the host.
DBG_SLIDERS = """slider20:dbg_alive=-1<-1,99999,1>-dbg alive
slider21:dbg_agc=-999<-999,999,0.01>-dbg agc
slider22:dbg_threshv=-999<-999,99999,0.001>-dbg threshv
slider23:dbg_done=-1<-1,9999,1>-dbg done
"""

# Appended to the END of @gfx. Exercises the real automation path: set a
# slider the way a knob does, then automate it by the same bitmask form.
DBG_TAIL = """
// ---- generated by tools/gfx_test.py, not part of the shipped plugin ----
gdbg_f += 1;
gdbg_f == 10 ? (
  // Drive the REAL commit path a knob uses -- not a copy of it.
  agc_mode = 3;    g_commit(7);      // Mid/Side
  lthr_db = -33.5; g_commit(1);
);
gdbg_f == 25 ? (
  // extremes, then keep drawing: catches NaN/inf in the dial scaling, which
  // would otherwise only show up as a dead panel
  lbias_pct = 0; rbias_pct = 100; lrms_us = 1; rrms_us = 10000;
  ratio_max = 2; sc_hz = 500; link_pct = 0; trim_db = -24; hist_s = 30;
  ltc = 6; rtc = 1; g_commit(3); g_commit(10); g_commit(17);
  agc_mode = 3; lthr_db = -33.5; g_commit(7); g_commit(1);
);
gdbg_f == 45 ? (
  dbg_alive   = gdbg_f;
  dbg_agc     = agc;              // audio-side: 1 only if recalc() ran
  dbg_threshv = l.threshv*1000;   // audio-side coefficient
  dbg_done    = 1;
  slider_automate(2^(20-1)); slider_automate(2^(21-1));
  slider_automate(2^(22-1)); slider_automate(2^(23-1));
);
"""


def build_debug():
    src = open(SRC).read()
    i = src.index("\nin_pin:")
    src = src[:i] + "\n" + DBG_SLIDERS + src[i:]
    src = src.rstrip("\n") + "\n" + DBG_TAIL
    open(os.path.join(RES, "Effects", DBG), "w").write(src)


def main():
    os.makedirs(WORK, exist_ok=True)
    out = os.path.join(WORK, "gfx_result.txt")
    if os.path.exists(out):
        os.remove(out)

    # isolated resource dir: reaper.ini is never touched, and a stale
    # "faultyproject" flag there cannot pop a modal and hang the run
    res = os.path.join(WORK, "gfxres")
    shutil.rmtree(res, ignore_errors=True)
    os.makedirs(res)
    ini = [l for l in open(os.path.join(RES, "reaper.ini"))
           if not l.startswith("faultyproject=")]
    open(os.path.join(res, "reaper.ini"), "w").writelines(ini)
    for f in ("reaper-license.rk",):
        if os.path.exists(os.path.join(RES, f)):
            shutil.copy(os.path.join(RES, f), os.path.join(res, f))
    for d in ("Effects", "Data"):
        os.symlink(os.path.join(RES, d), os.path.join(res, d))

    lua = os.path.join(WORK, "gfx_probe.lua")
    open(lua, "w").write('''
local OUT = %r
reaper.InsertTrackAtIndex(0, false)
local tr = reaper.GetTrack(0, 0)
local fx = reaper.TrackFX_AddByName(tr, %r, false, -1)
if fx < 0 then
  local f = io.open(OUT, "w"); f:write("ADD_FAILED\\n"); f:close(); return
end
reaper.TrackFX_Show(tr, fx, 3)          -- float it: @gfx only runs when shown
local names, n = {}, reaper.TrackFX_GetNumParams(tr, fx)
for i = 0, n - 1 do
  local _, nm = reaper.TrackFX_GetParamName(tr, fx, i, "")
  names[nm] = i
end
local tries = 0
local function get(nm)
  if names[nm] == nil then return -12345 end
  return reaper.TrackFX_GetParam(tr, fx, names[nm])
end
local function poll()
  tries = tries + 1
  if get("dbg done") >= 0 or tries > 400 then
    local f = io.open(OUT, "w")
    f:write(string.format("alive=%%d agc=%%.3f threshv=%%.3f done=%%d tries=%%d\\n",
      get("dbg alive"), get("dbg agc"), get("dbg threshv"), get("dbg done"), tries))
    f:close()
    return
  end
  reaper.defer(poll)
end
poll()
''' % (out, DBG))

    build_debug()
    proc = subprocess.Popen(
        ["reaper", "-cfgfile", os.path.join(res, "reaper.ini"), lua],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        t0 = time.time()
        while time.time() - t0 < 60 and not os.path.exists(out):
            time.sleep(0.25)
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
        if not os.environ.get("VARIMU_KEEP_DBG"):
            os.remove(os.path.join(RES, "Effects", DBG))

    if not os.path.exists(out):
        print("gfx            FAIL  no result -- REAPER never ran the panel")
        return 1
    txt = open(out).read().strip()
    if "ADD_FAILED" in txt:
        print("gfx            FAIL  debug build would not load: " + txt)
        return 1
    kv = dict(p.split("=") for p in txt.split())
    alive = float(kv["alive"])
    agc = float(kv["agc"])
    threshv = float(kv["threshv"])
    # exp(-33.5 * ln(10)/20) * 1000
    want = math.exp(-33.5 * 0.11512925464970229) * 1000
    checks = [
        ("@gfx compiles and runs", alive >= 45),
        ("Mode knob reaches the audio path (agc==1)", abs(agc - 1) < 0.01),
        ("Threshold knob reaches the audio path (l.threshv==%.3f)" % want,
         abs(threshv - want) < 0.05),
    ]
    bad = [n for n, ok in checks if not ok]
    print("gfx            %s  %s" % ("PASS" if not bad else "FAIL", txt))
    for n, ok in checks:
        print("    %s %s" % ("ok  " if ok else "FAIL", n))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
