#!/usr/bin/env python3
"""GUI test for the IR browser in Magnolius_ConvolutionReverb.jsfx.

@gfx runs on the UI thread and never runs in an offline render, so
tools/render_test.py cannot reach the browser at all. This drives it for real:
it generates a debug build from the shipped source, opens the FX window in a
throwaway REAPER instance, and makes @gfx run its own search/filter steps and
publish the results through hidden sliders, which a ReaScript reads back.

That covers the parts with actual logic in them — the index is visible to the
UI thread, case-insensitive multi-term matching, and folder filtering — against
expectations computed here from the same index file. It does NOT check that
anything is legible: nothing available here can screenshot a JSFX graphics pane
under Wayland (xwd misses it and x11grab returns black), so how it LOOKS is
still on you.

Runs in an isolated resource directory (-cfgfile), so your REAPER config is
untouched. Needs a graphical session.

Usage: gfx_test.py            (CONVRVB_KEEP_DBG=1 keeps the generated build)
"""
import os
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "Magnolius_ConvolutionReverb.jsfx")
RES = os.path.expanduser("~/.config/REAPER")
IDX = os.path.join(RES, "Data", "ConvReverbIRs.idx")
WORK = os.environ.get("CONVRVB_TEST_DIR",
                      os.path.expanduser("~/.cache/convrvb-rendertest"))
DBG = "_ConvRvbGfxDbg.jsfx"

# Four hidden (-prefixed) sliders carry results out of @gfx. slider_automate is
# the only channel the UI thread has to the host, and it works for numeric
# sliders — just not for file sliders, which is the whole reason the browser
# exists.
DBG_SLIDERS = """slider20:dbg_vocal=-1<-1,9999,1>-dbg vocal
slider21:dbg_two=-1<-1,9999,1>-dbg two-term
slider22:dbg_fold=-1<-1,9999,1>-dbg folder 0
slider23:dbg_all=-1<-1,9999,1>-dbg all
"""

# Appended to the END of @gfx. Steps a frame counter so each filter runs on a
# frame of its own, then publishes. Frame numbers are generous: the pane may
# not repaint every vblank.
DBG_TAIL = """
// ---- generated by tools/gfx_test.py, not part of the shipped plugin ----
gdbg_f += 1;
gdbg_f == 10 ? ( strcpy(#g_query, "vocal"); g_dirty = 1; );
gdbg_f == 20 ? ( dbg_vocal = g_nflt; strcpy(#g_query, "hall large"); g_dirty = 1; );
gdbg_f == 30 ? ( dbg_two = g_nflt; strcpy(#g_query, ""); g_fold = 0; g_dirty = 1; );
gdbg_f == 40 ? ( dbg_fold = g_nflt; g_fold = -1; g_dirty = 1; );
gdbg_f == 50 ? (
  dbg_all = g_nflt;
  slider_automate(dbg_vocal); slider_automate(dbg_two);
  slider_automate(dbg_fold); slider_automate(dbg_all);
);
"""


def expectations():
    names = [l.rstrip("\n\r") for l in open(IDX) if l.strip()]

    def has_all(name, terms):
        return all(t in name.lower() for t in terms)

    folders = []
    for n in names:
        f = n.rsplit("/", 1)[0] if "/" in n else ""
        if f not in folders:
            folders.append(f)
    fold0 = folders[0]
    return {
        "vocal": sum(1 for n in names if has_all(n, ["vocal"])),
        "two": sum(1 for n in names if has_all(n, ["hall", "large"])),
        "fold": sum(1 for n in names
                    if (n.rsplit("/", 1)[0] if "/" in n else "") == fold0),
        "all": len(names),
    }


def build_debug():
    src = open(SRC).read()
    i = src.index("\nin_pin:")
    src = src[:i] + "\n" + DBG_SLIDERS + src[i:]
    src = src.rstrip("\n") + "\n" + DBG_TAIL
    open(os.path.join(RES, "Effects", DBG), "w").write(src)


def main():
    if not os.path.exists(IDX):
        sys.exit("no index at %s — run tools/index_irs.py first" % IDX)
    exp = expectations()
    os.makedirs(WORK, exist_ok=True)
    out = os.path.join(WORK, "gfx_result.txt")
    if os.path.exists(out):
        os.remove(out)

    # isolated resource dir: your reaper.ini is never touched, and a stale
    # "faultyproject" flag there cannot pop a modal and hang the run
    res = os.path.join(WORK, "gfxres")
    shutil.rmtree(res, ignore_errors=True)
    os.makedirs(res)
    ini = [l for l in open(os.path.join(RES, "reaper.ini"))
           if not l.startswith("faultyproject=")]
    open(os.path.join(res, "reaper.ini"), "w").writelines(ini)
    for f in ("reaper-license.rk",):
        if os.path.exists(os.path.join(RES, f)):
            shutil.copy(os.path.join(RES, f), os.path.join(res, f))
    for d in ("Effects", "Data"):
        os.symlink(os.path.join(RES, d), os.path.join(res, d))

    lua = os.path.join(WORK, "gfx_probe.lua")
    open(lua, "w").write('''
local OUT = %r
reaper.InsertTrackAtIndex(0, false)
local tr = reaper.GetTrack(0, 0)
local fx = reaper.TrackFX_AddByName(tr, %r, false, -1)
reaper.TrackFX_Show(tr, fx, 3)          -- float it: @gfx only runs when shown
local names, n = {}, reaper.TrackFX_GetNumParams(tr, fx)
for i = 0, n - 1 do
  local _, nm = reaper.TrackFX_GetParamName(tr, fx, i, "")
  names[nm] = i
end
local tries = 0
local function poll()
  tries = tries + 1
  local function get(nm) return reaper.TrackFX_GetParam(tr, fx, names[nm]) end
  -- "dbg all" is the LAST value @gfx publishes, so waiting on it means the
  -- earlier three are already settled
  local v = get("dbg all")
  if v >= 0 or tries > 400 then
    local f = io.open(OUT, "w")
    f:write(string.format("vocal=%%d two=%%d fold=%%d all=%%d tries=%%d\\n",
      get("dbg vocal"), get("dbg two-term"), get("dbg folder 0"),
      get("dbg all"), tries))
    f:close()
    return
  end
  reaper.defer(poll)
end
poll()
''' % (out, DBG))

    build_debug()
    proc = subprocess.Popen(
        ["reaper", "-cfgfile", os.path.join(res, "reaper.ini"),
         "-newinst", "-nosplash", lua],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        deadline = time.time() + 90
        while time.time() < deadline and not os.path.exists(out):
            time.sleep(1)
        got = open(out).read().strip() if os.path.exists(out) else None
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=15)
        except subprocess.TimeoutExpired:
            proc.kill()
        if not os.environ.get("CONVRVB_KEEP_DBG"):
            try:
                os.remove(os.path.join(RES, "Effects", DBG))
            except OSError:
                pass

    if not got:
        print("gfx          FAIL  no result — @gfx never ran or never published")
        sys.exit(1)
    vals = dict(kv.split("=") for kv in got.split())
    ok = all(int(vals[k]) == exp[k] for k in ("vocal", "two", "fold", "all"))
    print("gfx          %s  %s  (expected vocal=%d two=%d fold=%d all=%d)"
          % ("PASS" if ok else "FAIL", got, exp["vocal"], exp["two"],
             exp["fold"], exp["all"]))
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
