-- AutoTilt -- the compiled EEL kernel, on signals with known answers.
--
-- Runs inside REAPER because it needs ReaImGui to compile the EEL, but it
-- never opens an audio accessor: every signal here is generated in Lua and
-- pushed straight into the kernel's input buffer. That is deliberate -- it
-- separates "is the DSP right" from "did the audio arrive", which are the two
-- questions that otherwise mask each other.
--
-- The assertion that earns this file's keep is the response sweep: the render
-- biquads, measured on real sine waves, against solve.lua's analytic |H(f)|.
-- Those are the two halves the whole design rests on agreeing about -- the
-- prediction that chooses the gain, and the filter that applies it -- and
-- nothing else checks that they do.

local src = debug.getinfo(1, "S").source:match("^@(.+)$")
local script_dir = src:match("^(.*[/\\])"):gsub("test[/\\]$", "")

local out, pass, fail = {}, 0, 0
local function say(s) out[#out + 1] = s end
local function section(s) say("-- " .. s) end

local function ok(cond, name, extra)
  if cond then
    pass = pass + 1
    say("  ok    " .. name)
  else
    fail = fail + 1
    say("  FAIL  " .. name .. (extra and ("  -- " .. extra) or ""))
  end
end

local function near(a, b, tol, name)
  ok(a and math.abs(a - b) <= tol, name,
     string.format("%s vs %s (tol %s)", tostring(a), tostring(b), tostring(tol)))
end

local function report()
  say(string.format("\nselftest: %d passed, %d failed", pass, fail))
  reaper.ShowConsoleMsg(table.concat(out, "\n") .. "\n")
  if os.exit then os.exit(fail == 0 and 0 or 1) end
end

-- Anything that stops the run is a failure, not a quiet pass: a green exit has
-- to mean the thing was verified, not that the script declined to look.
local function bail(msg)
  fail = fail + 1
  say("  FAIL  " .. msg)
  end

if not reaper.ImGui_GetBuiltinPath then bail("ReaImGui is not installed") return end
package.path = script_dir .. "?.lua;" .. script_dir .. "test/?.lua;"
            .. reaper.ImGui_GetBuiltinPath() .. "/?.lua;" .. package.path

local ImGui    = require "imgui" "0.9"
local Config   = require "at.config"
local Kernel   = require "at.kernel"
local Spectrum = require "at.spectrum"
local Solve    = require "at.solve"

local RATE = 48000
local ctx = ImGui.CreateContext("AutoTilt selftest")

local cfg = Config.new()
cfg.fft_size, cfg.ana_hop = 1024, 256

local k, kerr = Kernel.build(ImGui, ctx, script_dir, 1, cfg)
if not k then bail("the kernel would not build: " .. tostring(kerr)) return end
k:set_hop(Config.hop(cfg))

local N = k.fft_size

------------------------------------------------------------------- helpers ----

-- Push `n` samples generated by gen(i) (0-based sample index) through a task.
local function feed(n, gen, task, i0)
  i0 = i0 or 0
  local done = 0
  local tail, tail_in
  while done < n do
    local blk = math.min(k.block, n - done)
    local src = {}
    for j = 1, blk do
      src[j] = gen(i0 + done + j - 1)
      k.inbuf[j] = src[j]
    end
    if task == "analyze" then
      k:analyze(blk)
    else
      k:render(blk)
      tail, tail_in = k.outbuf.table(1, blk), src
    end
    done = done + blk
  end
  return tail, tail_in
end

-- Snap a frequency so a whole number of cycles fits the measurement window.
-- Without this the RMS of a partial final cycle is not the signal's RMS, and
-- the sweep below disagrees with the prediction by up to 0.03 dB at 60 Hz --
-- an artefact of the measurement, not of the filter.
local WINDOW = 8192
local function snap(hz)
  local m = math.max(1, math.floor(hz * WINDOW / RATE + 0.5))
  return m * RATE / WINDOW
end

local function sine(amp, hz)
  return function(i) return amp * math.sin(2 * math.pi * hz * i / RATE) end
end

local function rms(t)
  local s = 0
  for i = 1, #t do s = s + t[i] * t[i] end
  return math.sqrt(s / #t)
end

------------------------------------------------------------------ the setup ----
section("setup")
ok(k.nbins == N // 2 + 1, "nbins is half the transform plus one", tostring(k.nbins))
ok(k.heap_used > 0, "the kernel allocated a heap")
say(string.format("        heap %.2f MB, FFT %d, %d bins",
    k.heap_used * 8 / 1048576, N, k.nbins))
near(k.heap_used, Kernel.heap_doubles(N, 1), N,
     "the heap matches what config predicted")

--------------------------------------------------------------- the analysis ----
section("analysis: level bucketing and the transform")
do
  k:reset_analysis()
  -- A full-scale sine on a bin centre: RMS is 1/sqrt(2), so the frame level is
  -- 10*log10(0.5) = -3.0103 dBFS and the bucket is that above LEV0.
  local bin = 64
  local hz = bin * RATE / N
  feed(N * 12, sine(1.0, hz), "analyze")

  local frames = k:frames()
  ok(frames > 30, "the hop produced the expected number of frames", tostring(frames))

  local counts = k:counts()
  local want = math.floor(-3.0103 - Config.LEV0 + 0.5)
  ok((counts[want] or 0) > 0,
     string.format("a full-scale sine buckets at %d dBFS", want + Config.LEV0),
     "bucket " .. want .. " holds " .. tostring(counts[want]))

  local total = 0
  for lev = 0, k.nlev - 1 do total = total + counts[lev] end
  ok(total == frames, "every frame landed in exactly one bucket",
     string.format("%d vs %d", total, frames))

  -- The transform: all the energy in one bin, and Parseval's sum reading back
  -- as the sine's actual mean square.
  local rows = k:cube()
  local row = rows[want]
  if not row then
    ok(false, "the loud bucket has a spectrum row")
  else
    local peak, peak_k = -1, -1
    for i = 1, k.nbins do
      if row[i] > peak then peak, peak_k = row[i], i - 1 end
    end
    ok(peak_k == bin, string.format("the peak is at bin %d", bin), tostring(peak_k))

    local nf = counts[want]
    local tot = row[1] + row[k.nbins]
    for i = 2, k.nbins - 1 do tot = tot + 2 * row[i] end
    tot = tot / (1 * N * N * 0.375) / nf
    near(tot, 0.5, 0.02, "Parseval reads back the sine's mean square")

    -- The neighbours of a bin-centred tone in a Hann window carry a quarter of
    -- its power each and everything else is leakage; anything else means the
    -- window or the twiddles are wrong.
    ok(row[bin] > 0 and row[bin + 2] > 0, "the Hann skirts are populated")
    ok(row[bin + 8] < peak * 1e-6, "and the far bins are not", tostring(row[bin + 8] / peak))
  end
end

section("analysis: two levels bucket apart")
do
  k:reset_analysis()
  local hz = 64 * RATE / N
  feed(N * 8, sine(1.0, hz), "analyze")
  local mid = k:frames()
  feed(N * 8, sine(0.1, hz), "analyze", N * 8)

  local counts = k:counts()
  local occupied = {}
  for lev = 0, k.nlev - 1 do
    if counts[lev] > 0 then occupied[#occupied + 1] = lev end
  end
  -- Three: the loud run, the quiet run, and a handful of frames straddling the
  -- boundary while the ring still holds some of each.
  ok(#occupied >= 2, "two levels occupy at least two buckets",
     "buckets: " .. table.concat(occupied, ","))
  ok(occupied[#occupied] - occupied[1] >= 19 and
     occupied[#occupied] - occupied[1] <= 21,
     "and they sit 20 dB apart",
     tostring(occupied[#occupied] - occupied[1]))
  ok(mid > 0, "the first run produced frames")

  -- The gate has to be able to separate them.
  local rows, cnts = k:cube()
  local ana = Spectrum.build(rows, cnts, k.nbins, k.nlev, k.lev0)
  local gcfg = Config.new()
  gcfg.gate_db, gcfg.gate_pct = 10, 95
  local _, kept, tot = Spectrum.gated(ana, gcfg)
  ok(kept < tot, "a 10 dB gate excludes the quiet run",
     string.format("%d of %d", kept, tot))
end

------------------------------------------------------------------ the render ----
section("render: G = 0 is a bit-exact pass-through")
do
  local plan = Solve.plan(nil, cfg, RATE, 0, N, RATE)
  plan.makeup = 1
  k:reset_stream()
  k:set_plan(plan)

  -- Deterministic, broadband, and nothing near a special value.
  local function noise(i)
    local x = math.sin(i * 12.9898) * 43758.5453
    return (x - math.floor(x)) * 2 - 1
  end
  local n = 4096
  local o = feed(n, noise, "render")
  local worst, worst_i = 0, -1
  for j = 1, n do
    local d = math.abs(o[j] - noise(j - 1))
    if d > worst then worst, worst_i = d, j end
  end
  ok(worst == 0, "every sample comes back identical",
     string.format("worst %g at sample %d", worst, worst_i))
end

section("render: the makeup gain is applied exactly")
do
  local plan = Solve.plan(nil, cfg, RATE, 0, N, RATE)
  plan.makeup = 0.25
  k:reset_stream()
  k:set_plan(plan)
  local o = feed(1024, function(i) return (i % 7) / 7 - 0.5 end, "render")
  local worst = 0
  for j = 1, 1024 do
    worst = math.max(worst, math.abs(o[j] - ((j - 1) % 7 / 7 - 0.5) * 0.25))
  end
  ok(worst == 0, "output is exactly input times the makeup gain", tostring(worst))
end

section("render: measured response matches solve.lua's prediction")
do
  local freqs = {}
  for _, f in ipairs({ 60, 120, 250, 500, 1000, 2000, 4000, 8000, 12000 }) do
    freqs[#freqs + 1] = snap(f)
  end
  local gains = { -9, -4, 3, 8 }
  local worst, worst_at = 0, ""
  for _, G in ipairs(gains) do
    local plan = Solve.plan(nil, cfg, RATE, G, N, RATE)
    plan.makeup = 1
    local lo, hi = Solve.pair(cfg, RATE, G)
    for _, hz in ipairs(freqs) do
      k:reset_stream()
      k:set_plan(plan)
      -- Three blocks in, measure the last: two biquads settle in far less.
      local o, i = feed(WINDOW * 3, sine(0.5, hz), "render")
      local measured = 20 * math.log(rms(o) / rms(i), 10)
      local predicted = 10 * math.log(Solve.pair_response_sq(lo, hi, hz, RATE), 10)
      local d = math.abs(measured - predicted)
      if d > worst then
        worst, worst_at = d, string.format("%.1f Hz at %+d dB", hz, G)
      end
    end
  end
  ok(worst < 0.01, "every point agrees to better than 0.01 dB",
     string.format("worst %.4f dB at %s", worst, worst_at))
  say(string.format("        worst disagreement %.4f dB (%s)", worst, worst_at))
end

section("render: unity at the pivot, and the full span across it")
do
  for _, G in ipairs({ -6, 5 }) do
    local plan = Solve.plan(nil, cfg, RATE, G, N, RATE)
    plan.makeup = 1
    local function at(hz)
      k:reset_stream()
      k:set_plan(plan)
      local o, i = feed(WINDOW * 3, sine(0.5, snap(hz)), "render")
      return 20 * math.log(rms(o) / rms(i), 10)
    end
    near(at(cfg.pivot_hz), 0, 0.01,
         string.format("G=%+d: unity at the pivot", G))
    near(at(16000) - at(40), G, 0.6,
         string.format("G=%+d: spans G dB from 40 Hz to 16 kHz", G))
  end
end

------------------------------------------------------------ the panel's API ----
-- The stub in test/ui_frame.lua answers every call, so it cannot notice a name
-- that does not exist in the real library -- a symbol renamed between ReaImGui
-- versions raises only when a user opens the panel. This is the cheap half of
-- that check: every ImGui.X the panel names has to be there for real. It does
-- not check arities, which still need the panel opened by hand once.
section("the panel's ImGui symbols")
do
  local fh = io.open(script_dir .. "at/ui.lua", "rb")
  if not fh then
    ok(false, "at/ui.lua could be read for the symbol scan")
  else
    local text = fh:read("a")
    fh:close()
    local seen, missing, n = {}, {}, 0
    for name in text:gmatch("ImGui%.([%w_]+)") do
      if not seen[name] then
        seen[name] = true
        n = n + 1
        if ImGui[name] == nil then missing[#missing + 1] = name end
      end
    end
    table.sort(missing)
    ok(n > 20, "the scan found the panel's calls", tostring(n) .. " symbols")
    ok(#missing == 0, "every ImGui symbol the panel names exists",
       "missing: " .. table.concat(missing, ", "))
    say(string.format("        %d distinct ImGui symbols, all present", n))
  end
end

report()
